# Generated by Django 3.2.7 on 2021-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('choose_1', models.CharField(max_length=150, null=True)),
                ('choose_2', models.CharField(max_length=150, null=True)),
                ('choose_3', models.CharField(max_length=150, null=True)),
                ('choose_4', models.CharField(max_length=150, null=True)),
                ('answer', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
